contact_links:
  - name: General support and product feedback
    url: https://support.detahard.io
    about: Please do not use this Github repository for technical support. Contact detahard support directly or visit our community forum at forum.detahard.io.
